import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import '@boulder.best/shadcn/globals.css';

export const metadata: Metadata = {
	description: 'Generated by create-nx-workspace',
	title: 'Welcome to clim.bz',
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
